CREATE TABLE APPLICANT (
  ID BIGINT NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  AGE DECIMAL(19, 2) NOT NULL,
  CREDIT_SCORE DECIMAL(19, 2) NOT NULL,

  PRIMARY KEY (ID)
);
CREATE TABLE CREDIT_ISSUE_TYPE (
  ID BIGINT NOT NULL,
  NAME VARCHAR(255) NOT NULL,

  PRIMARY KEY (ID)
);
CREATE TABLE APPLICANT_ISSUE (
  APP_ID BIGINT NOT NULL,
  ISSUE_ID BIGINT NOT NULL,

  PRIMARY KEY (APP_ID, ISSUE_ID)
)