DELETE FROM APPLICANT;
INSERT INTO APPLICANT(ID, NAME, AGE) VALUES (1, 'Amy', 38);
INSERT INTO APPLICANT(ID, NAME, AGE) VALUES (2, 'Amy', 18);
INSERT INTO APPLICANT(ID, NAME, AGE) VALUES (3, 'Amy', 25);
INSERT INTO APPLICANT(ID, NAME, AGE) VALUES (4, 'Amy', 37);
