DELETE FROM APPLICANT;
INSERT INTO APPLICANT(ID, NAME, AGE, CREDIT_SCORE) VALUES (0, 'Amy', 38, 100);
INSERT INTO APPLICANT(ID, NAME, AGE, CREDIT_SCORE) VALUES (1, 'Bill', 18, 65);
INSERT INTO APPLICANT(ID, NAME, AGE, CREDIT_SCORE) VALUES (2, 'Charlie', 65, 80);

DELETE FROM CREDIT_ISSUE_TYPE;
INSERT INTO CREDIT_ISSUE_TYPE(ID, NAME) VALUES (0, 'Late payment');
INSERT INTO CREDIT_ISSUE_TYPE(ID, NAME) VALUES (1, 'Card rejection');
INSERT INTO CREDIT_ISSUE_TYPE(ID, NAME) VALUES (2, 'Default on obligations');
INSERT INTO CREDIT_ISSUE_TYPE(ID, NAME) VALUES (3, 'Bankruptcy');

DELETE FROM APPLICANT_ISSUE;
-- Amy
INSERT INTO APPLICANT_ISSUE(APP_ID, ISSUE_ID) VALUES (0, 0);
-- Bill
INSERT INTO APPLICANT_ISSUE(APP_ID, ISSUE_ID) VALUES (1, 1);
INSERT INTO APPLICANT_ISSUE(APP_ID, ISSUE_ID) VALUES (1, 2);
-- Charlie
INSERT INTO APPLICANT_ISSUE(APP_ID, ISSUE_ID) VALUES (2, 0);
INSERT INTO APPLICANT_ISSUE(APP_ID, ISSUE_ID) VALUES (2, 2);
INSERT INTO APPLICANT_ISSUE(APP_ID, ISSUE_ID) VALUES (2, 3);
